### ISSUE TITLE
SCS Service Registry bound app spams SCS UAA Identity Zone when Service Instance is deleting without the app knowing

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/spring-cloud-services-connector#72]
The steps to reproduce:
1. Deploy Service Registry instance `cf cs p-service-registry standard my-sr`
2. Deploy client app with SCS Connector and bind to `my-sr`
3. After client apps starts successfully, run `cf logs [appname]` to tail output
3. Get `my-sr` SI-GUID from dashboard URL via `cf service my-sr` output
4. Delete service instance using `cf curl -X DELETE /v2/service_instances/[SI-GUID]?recursive=true

Now the client app's log output will start to periodically (every few seconds) loop something like the following exception:

```
   2018-07-20T11:38:22.34-0700 [APP/PROC/WEB/0] OUT Caused by: org.springframework.web.client.HttpClientErrorException: 401 Unauthorized
   2018-07-20T11:38:22.34-0700 [APP/PROC/WEB/0] OUT     at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:94) ~[spring-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
   2018-07-20T11:38:22.34-0700 [APP/PROC/WEB/0] OUT     at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:79) ~[spring-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
   2018-07-20T11:38:22.34-0700 [APP/PROC/WEB/0] OUT     at org.springframework.security.oauth2.client.token.OAuth2AccessTokenSupport$AccessTokenErrorHandler.handleError(OAuth2AccessTokenSupport.java:246) ~[spring-security-oauth2-2.3.3.RELEASE.jar!/:na]
   2018-07-20T11:38:22.34-0700 [APP/PROC/WEB/0] OUT     at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
   2018-07-20T11:38:22.34-0700 [APP/PROC/WEB/0] OUT     at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:766) ~[spring-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
   2018-07-20T11:38:22.34-0700 [APP/PROC/WEB/0] OUT     at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:724) ~[spring-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
   2018-07-20T11:38:22.34-0700 [APP/PROC/WEB/0] OUT     at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:690) ~[spring-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
   2018-07-20T11:38:22.34-0700 [APP/PROC/WEB/0] OUT     at org.springframework.security.oauth2.client.token.OAuth2AccessTokenSupport.retrieveToken(OAuth2AccessTokenSupport.java:137) ~[spring-security-oauth2-2.3.3.RELEASE.jar!/:na]
   2018-07-20T11:38:22.34-0700 [APP/PROC/WEB/0] OUT     ... 32 common frames omitted
   2018-07-20T11:38:22.34-0700 [APP/PROC/WEB/0] OUT 2018-07-20 18:38:22.348  WARN 15 --- [tbeatExecutor-0] c.n.d.s.t.d.RetryableEurekaHttpClient    : Request execution failed with message: Error requesting access token.
   2018-07-20T11:38:22.35-0700 [APP/PROC/WEB/0] OUT 2018-07-20 18:38:22.349 ERROR 15 --- [tbeatExecutor-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_GREETER-MESSAGES/greeter-messages-cs.apps.moscow.cf-app.com:[GUID] - was unable to send heartbeat!
   2018-07-20T11:38:22.35-0700 [APP/PROC/WEB/0] OUT com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
   2018-07-20T11:38:22.35-0700 [APP/PROC/WEB/0] OUT     at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112) ~[eureka-client-1.9.2.jar!/:1.9.2]
   2018-07-20T11:38:22.35-0700 [APP/PROC/WEB/0] OUT     at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89) ~[eureka-client-1.9.2.jar!/:1.9.2]
   2018-07-20T11:38:22.35-0700 [APP/PROC/WEB/0] OUT     at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$3.execute(EurekaHttpClientDecorator.java:92) ~[eureka-client-1.9.2.jar!/:1.9.2]
   2018-07-20T11:38:22.35-0700 [APP/PROC/WEB/0] OUT     at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77) ~[eureka-client-1.9.2.jar!/:1.9.2]
   2018-07-20T11:38:22.35-0700 [APP/PROC/WEB/0] OUT     at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89) ~[eureka-client-1.9.2.jar!/:1.9.2]
   2018-07-20T11:38:22.35-0700 [APP/PROC/WEB/0] OUT     at com.netflix.discovery.DiscoveryClient.renew(DiscoveryClient.java:846) ~[eureka-client-1.9.2.jar!/:1.9.2]
   2018-07-20T11:38:22.35-0700 [APP/PROC/WEB/0] OUT     at com.netflix.discovery.DiscoveryClient$HeartbeatThread.run(DiscoveryClient.java:1399) [eureka-client-1.9.2.jar!/:1.9.2]
   2018-07-20T11:38:22.35-0700 [APP/PROC/WEB/0] OUT     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_172]
   2018-07-20T11:38:22.35-0700 [APP/PROC/WEB/0] OUT     at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_172]
   2018-07-20T11:38:22.35-0700 [APP/PROC/WEB/0] OUT     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_172]
   2018-07-20T11:38:22.35-0700 [APP/PROC/WEB/0] OUT     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_172]
   2018-07-20T11:38:22.35-0700 [APP/PROC/WEB/0] OUT     at java.lang.Thread.run(Thread.java:748) [na:1.8.0_172]
```

I'm not sure what the best way is to stop a client app from spamming UAA after it's Service Registry is deleted along with it's service keys and bindings? Maybe a backoff request increasing the amount of time between requests for UAA? That only makes the issue smaller and doesn't resolve it entirely. Thoughts?

**Comment by AlbertoImpl** [comment]
Did another test just stopping the app and even if we had access to UAA, we will see the same amount of request ocurring, but now hitting the unexisting route and returning a 404:
```
 GET request for "https://eureka-e815e9aa-0eea-45ba-9000-453aa393757f.apps.gold.springapps.io/eureka/apps/delta" resulted in 404 (Not Found); invoking error handler
```
If after this, we delete the app via the `curl -X DELETE` we are again in the same problem not being able to get the token.

**Comment by AlbertoImpl** [comment]
After performing some tests and having some conversations with the eureka OSS team:

- Even if we can change the way eureka works today, which considers the eureka-server being down a disaster scenario, it won't help current apps spamming UAA
- Restaging the apps solves the UAA problem since they will just do a request to a server they can't find.

However, this raises some concerns:

- CloudOps should identify and restage all the apps by themselves
- We will have to extend the reaper to restage bind apps after deleting the SI and it feels like it's out of our team scope.

**Comment by csterwa** [comment]
Closing with no suitable change at this time.
