### ISSUE TITLE
Release SC Connectors 1.2.7

### ISSUE THREAD

**Issue by spikymonkey** [pivotal-cf/spring-cloud-services-connector#84]
This should incorporate https://github.com/spring-cloud/spring-cloud-connectors/pull/240 or its replacement.

required by #83

**Comment by spikymonkey** [comment]
First of all let's establish a baseline so we can check for regressions.

Spring Music with SC Connectors 1.2.6.RELEASE compatibility:
- [ ] PWS ClearDB (mysql)
- [ ] PWS ElephantSQL (postgres)
- [ ] PCF MySQL 1.x
- [ ] PCF MySQL 2.x
- [ ] PCF Azure MySQL
- [ ] PCF Azure Postgres

**Comment by spikymonkey** [comment]
PCF mysql v1:

```
   2018-11-15T10:29:38.74+0000 [APP/PROC/WEB/0] OUT Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'cf_4fd95bac_ffbc_4bc5_97e4_d17e4a8f304a.album' doesn't exist
   2018-11-15T10:29:38.74+0000 [APP/PROC/WEB/0] OUT     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_181]
```

**Comment by spikymonkey** [comment]
PCF Azure MySQL:

```
   2018-11-15T10:33:55.68+0000 [APP/PROC/WEB/0] OUT Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'u9320a5da203.album' doesn't exist
   2018-11-15T10:33:55.68+0000 [APP/PROC/WEB/0] OUT     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_181]
   2018-11-15T10:33:55.68+0000 [APP/PROC/WEB/0] OUT     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_181]
   2018-11-15T10:33:55.68+0000 [APP/PROC/WEB/0] OUT     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_181]
```

**Comment by spikymonkey** [comment]
PCF Azure Postgres:

```
   2018-11-15T10:40:48.76+0000 [APP/PROC/WEB/0] OUT Caused by: java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
   2018-11-15T10:40:48.76+0000 [APP/PROC/WEB/0] OUT     at org.postgresql.Driver.notImplemented(Driver.java:683) ~[postgresql-42.2.2.jar!/:42.2.2]
   2018-11-15T10:40:48.76+0000 [APP/PROC/WEB/0] OUT     at org.postgresql.jdbc.PgConnection.createClob(PgConnection.java:1252) ~[postgresql-42.2.2.jar!/:42.2.2]
   2018-11-15T10:40:48.76+0000 [APP/PROC/WEB/0] OUT     ... 50 common frames omitted
```

**Comment by spikymonkey** [comment]
So this leaves PCF MySQL v1 and Azure MySQL to figure out. @scottfrederick says that the MySQL driver may never have supported PCF MySQL v1, so going to see if the Maria driver can help us here.

**Comment by spikymonkey** [comment]
Hmm... Maria doesn't like PCF MySQL v1 either:

```
   2018-11-15T11:17:51.87+0000 [APP/PROC/WEB/0] OUT Caused by: java.sql.SQLException: Table 'cf_4fd95bac_ffbc_4bc5_97e4_d17e4a8f304a.album' doesn't exist
   2018-11-15T11:17:51.87+0000 [APP/PROC/WEB/0] OUT Query is: select count(*) as col_0_0_ from album album0_
   2018-11-15T11:17:51.87+0000 [APP/PROC/WEB/0] OUT java thread: main
   2018-11-15T11:17:51.87+0000 [APP/PROC/WEB/0] OUT     at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:163) ~[mariadb-java-client-2.3.0.jar!/:na]
   2018-11-15T11:17:51.87+0000 [APP/PROC/WEB/0] OUT     at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:280) ~[mariadb-java-client-2.3.0.jar!/:na]
   2018-11-15T11:17:51.87+0000 [APP/PROC/WEB/0] OUT     at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:223) ~[mariadb-java-client-2.3.0.jar!/:na]
   2018-11-15T11:17:51.87+0000 [APP/PROC/WEB/0] OUT     ... 67 common frames omitted
```

**Comment by spikymonkey** [comment]
The problem with MySQL v1 is that hibernate is defaulting to use MYISAM table engine which doesn't exist in the MariaDB version that backs the Pivotal MySQL v1 tile. It should be possible to override like this:

```
---
spring:
  profiles: mysql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
```

But for some reason, dropping this in the mysql profile config doesn't work. Weirdly, it does work if placed in the top-level config:

```
spring:
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
```

But that's clearly rubbish. Need to figure out why the `mysql` profile config isn't taking effect...

**Comment by scottfrederick** [comment]
When configuring the Hibernate dialect to `MySQL55Dialect` at the top-level of the configuration properties, the changes to Connectors works against PCF MySQL v1 and Azure MySQL. That's enough to verify that Connectors is setting up the connection correctly. The other problems listed above are related to properly configuring Hibernate in an application, and shouldn't block the Connectors release.
